# Generated by Django 6.0 on 2025-12-16 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RawFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("file_type", models.CharField(max_length=50)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "raw_file",
                    models.FileField(blank=True, null=True, upload_to="raw_files/"),
                ),
                ("raw_text", models.TextField(blank=True, null=True)),
                ("raw_json", models.JSONField(blank=True, null=True)),
                (
                    "customer_detected",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExtractedRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("po_number", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "customer_part",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("quantity", models.FloatField(blank=True, null=True)),
                ("open_qty", models.FloatField(blank=True, null=True)),
                ("need_date", models.DateField(blank=True, null=True)),
                ("promised_date", models.DateField(blank=True, null=True)),
                ("ship_date", models.DateField(blank=True, null=True)),
                ("full_row_json", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "raw_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="importer.rawfile",
                    ),
                ),
            ],
        ),
    ]
