# Generated by Django 6.0 on 2025-12-17 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("importer", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rawfile",
            options={
                "verbose_name": "Upload File",
                "verbose_name_plural": "Upload File",
            },
        ),
        migrations.AlterField(
            model_name="rawfile",
            name="file_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="rawfile",
            name="file_type",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="rawfile",
            name="raw_file",
            field=models.FileField(upload_to="raw_files/", verbose_name="Upload File"),
        ),
        migrations.CreateModel(
            name="ExtractionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("INFO", "INFO"),
                            ("WARNING", "WARNING"),
                            ("ERROR", "ERROR"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("context", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "raw_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="importer.rawfile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ZSODemand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kas_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "customer_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "site_location",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                ("incoterms", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "sales_type",
                    models.CharField(
                        blank=True,
                        help_text="Direct Sales / WH Movement",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "po_or_forecast",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("category", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "sub_category",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "customer_part",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("maini_part", models.CharField(blank=True, max_length=255, null=True)),
                ("open_qty", models.FloatField(blank=True, null=True)),
                ("unit_price", models.FloatField(blank=True, null=True)),
                ("currency", models.CharField(blank=True, max_length=10, null=True)),
                ("unit_price_inr", models.FloatField(blank=True, null=True)),
                ("total_inr", models.FloatField(blank=True, null=True)),
                ("doc_date", models.DateField(blank=True, null=True)),
                ("ship_date", models.DateField(blank=True, null=True)),
                ("sales_month", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "confidence_score",
                    models.FloatField(
                        blank=True, help_text="Accuracy score of mapping", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "extracted_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zso_records",
                        to="importer.extractedrecord",
                    ),
                ),
            ],
        ),
    ]
