# Generated by Django 6.0 on 2025-12-17 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("importer", "0002_alter_rawfile_options_alter_rawfile_file_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rawfile",
            options={},
        ),
        migrations.RemoveField(
            model_name="rawfile",
            name="customer_detected",
        ),
        migrations.AddField(
            model_name="zsodemand",
            name="mapping_notes",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="zsodemand",
            name="raw_file",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="zso_demands",
                to="importer.rawfile",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="extractedrecord",
            name="raw_file",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="extracted_records",
                to="importer.rawfile",
            ),
        ),
        migrations.AlterField(
            model_name="extractionlog",
            name="level",
            field=models.CharField(
                choices=[("INFO", "Info"), ("SUCCESS", "Success"), ("ERROR", "Error")],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="zsodemand",
            name="category",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="zsodemand",
            name="confidence_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="zsodemand",
            name="currency",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="zsodemand",
            name="extracted_record",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="zso",
                to="importer.extractedrecord",
            ),
        ),
        migrations.AlterField(
            model_name="zsodemand",
            name="sales_month",
            field=models.CharField(
                blank=True,
                help_text="YYYY-MM derived from ship date",
                max_length=7,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="zsodemand",
            name="sales_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="zsodemand",
            name="sub_category",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
