# Generated by Django 6.0 on 2025-12-17 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("importer", "0003_alter_rawfile_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rawfile",
            options={
                "verbose_name": "Upload File",
                "verbose_name_plural": "Upload Files",
            },
        ),
    ]
