# Generated by Django 5.2.9 on 2025-12-18 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0004_alter_rawfile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedrecord',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
