# Generated by Django 5.2.9 on 2025-12-23 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0005_extractedrecord_is_processed'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('total', models.IntegerField(default=0)),
                ('processed', models.IntegerField(default=0)),
                ('failed', models.IntegerField(default=0)),
                ('is_running', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
