# Generated by Django 5.2.9 on 2025-12-23 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0006_processprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rawfile',
            options={},
        ),
        migrations.AddField(
            model_name='rawfile',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who uploaded this file', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_files', to=settings.AUTH_USER_MODEL),
        ),
    ]
